### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by nickolay** [laktak/pipenv-shebang#2]
I see that 089d7c12039d85c5b0f270d6f37d75c3f0563539 added "multiplatform support" by installing a python script instead of a bash script when bash is not available.

This doesn't quite work on Windows by default, as the system does not know the extension-less `pipenv-shebang` file is executable.

The solution (also employed by pipenv itself) is apparently to rely on [automatic script creation](https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation) feature of setuptools (`setup(entry_points={"console_scripts": ["pipenv-shebang = my_package.some_module:main_func"]})`), which on Windows generates an exe file invoking the specified python function.

I guess this would involve changing pipenv-shebang to a proper python package instead of installing the scripts as `data_files`. After that the logical thing to do is to drop the bash script.

Do you agree with this solution?

**Comment by laktak** [comment]
Sorry, I did not see your issue.

The bash file is there to avoid the startup time of a second python instance. Maybe for Windows you could simply install a .bat. I don't use Python on Windows though anymore.
